version: '3.5'

services:
  postgres-odoo-base-15-01:
    container_name: postgres_odoo-base-15-01
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-odoo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-odoo}
      PGDATA: /data/postgres
    volumes:
       - ./db_data:/data/postgres
    ports:
      - "5431:5432"
    restart: unless-stopped

  odoo:
    container_name: odoo_app_15
    build: .
    depends_on:
      - postgres-odoo-base-15-01
    ports:
      - "8069:8069"
    volumes:
      # Ánh xạ thư mục addons trên máy thật vào container
      - ./addons:/mnt/extra-addons
      # Ánh xạ file cấu hình Odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
    environment:
      - HOST=postgres-odoo-base-15-01
      - USER=odoo
      - PASSWORD=odoo
    restart: unless-stopped